# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d68790d0dfa1034124c519fd169a88f3dce88c6804454ca0592e3ac53f8eba34cccbe03c8a72c771dbb62413261dc2195b77f1f4818d8f9834a6fcd9ce065104

test:
  secret_key_base: 8663e5ad259066255bcbf7b3a975352c2a49de79196049b62b15f1d29f8c9434c1cf5d42755f562f44b3c0a56bdab785bef3451e6e60e09b20d2b452e64013fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
